# Automatic differentiation in PyTorch

In [ ]:
import numpy as np
import torch
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

$$
f(x) = x^3
$$

$f'(x) = 3x^2$ -> $f'([1, 2]) = [3, 12]$

$f''(x) = 6x$ -> $f''([1, 2]) = [6, 12]$

In [ ]:
x = np.array([1, 2]).reshape(-1, 1)

x = torch.tensor(x, dtype=torch.float, requires_grad=True).to(device)

f = x**3

# torch.ones_like(f) 
# Since grad can be implicitly created only for scalar outputs,
# we have to specify grad_outputs to get a vector return.

# create_graph
# If True, graph of the derivative will be constructed, 
# allowing to compute higher order derivative products.

# [0]
# Return Type: Tuple[Tensor, …]
f_x = torch.autograd.grad(outputs=f, inputs=x, grad_outputs=torch.ones_like(f), create_graph=True)[0]

f_xx = torch.autograd.grad(f_x, x, torch.ones_like(f), create_graph=True)[0]

# print(type(f_x))
print('f_x')
print(f_x)

# print(type(f_xx))
print('f_xx')
print(f_xx)

f_x
tensor([[ 3.],
        [12.]], device='cuda:0', grad_fn=<MulBackward0>)
f_xx
tensor([[ 6.],
        [12.]], device='cuda:0', grad_fn=<MulBackward0>)


$$
f(x, t) = x^3 + xt + t^2
$$

$(x=[1,2], t=[3,4]) = ((x,t)=(1,3), (2,4))$

$f_x = 3x^2 + t$ -> $f_x = [6, 16]$

$f_t = x + 2t$ -> $f_t = [7, 10]$
 
$f_{xt} = 1$ -> $f_{xt} = [1, 1]$

$f_{tx} = 1$ -> $f_{tx} = [1, 1]$

$f_{xx} = 6x$ -> $f_{xx} = [6, 12]$

$f_{tt} = 2$ -> $f_{tt} = [2, 2]$

In [ ]:
x = np.array([1, 2]).reshape(-1, 1)
t = np.array([3, 4]).reshape(-1, 1)

x = torch.tensor(x, dtype=torch.float, requires_grad=True).to(device)
t = torch.tensor(t, dtype=torch.float, requires_grad=True).to(device)

f = x**3 + x*t + t**2

f_x = torch.autograd.grad(f, x, torch.ones_like(f), create_graph=True)[0]
f_t = torch.autograd.grad(f, t, torch.ones_like(f), create_graph=True)[0]

f_xt = torch.autograd.grad(f_x, t, torch.ones_like(f), create_graph=True)[0]
f_tx = torch.autograd.grad(f_t, x, torch.ones_like(f), create_graph=True)[0]

f_xx = torch.autograd.grad(f_x, x, torch.ones_like(f), create_graph=True)[0]
f_tt = torch.autograd.grad(f_t, t, torch.ones_like(f), create_graph=True)[0]

print('(x, t)')
print(torch.hstack([x, t]))

# print(type(f_x))
print('f_x')
print(f_x)

# print(type(f_t))
print('f_t')
print(f_t)

# print(type(f_xt))
print('f_xt')
print(f_xt)

# print(type(f_tx))
print('f_tx')
print(f_tx)

# print(type(f_xx))
print('f_xx')
print(f_xx)

# print(type(f_tt))
print('f_tt')
print(f_tt)

(x, t)
tensor([[1., 3.],
        [2., 4.]], device='cuda:0', grad_fn=<CatBackward0>)
f_x
tensor([[ 6.],
        [16.]], device='cuda:0', grad_fn=<AddBackward0>)
f_t
tensor([[ 7.],
        [10.]], device='cuda:0', grad_fn=<AddBackward0>)
f_xt
tensor([[1.],
        [1.]], device='cuda:0')
f_tx
tensor([[1.],
        [1.]], device='cuda:0')
f_xx
tensor([[ 6.],
        [12.]], device='cuda:0', grad_fn=<MulBackward0>)
f_tt
tensor([[2.],
        [2.]], device='cuda:0', grad_fn=<MulBackward0>)
