In [ ]:
import numpy as np

In [ ]:
# a is 5 x 3 matrix
a = np.random.random((5, 3))
a

array([[0.97915075, 0.29454376, 0.20319694],
       [0.16943012, 0.47999453, 0.97304161],
       [0.0578595 , 0.15649885, 0.00770776],
       [0.9294598 , 0.122083  , 0.09700409],
       [0.42281218, 0.44108726, 0.36235189]])

In [ ]:
# reduced QR factorization
(q, r) = np.linalg.qr(a)

In [ ]:
q

array([[-0.68664483,  0.0566785 , -0.09255171],
       [-0.11881553, -0.74328582,  0.63481197],
       [-0.04057488, -0.24080918, -0.50885539],
       [-0.65179827,  0.33029257,  0.24878636],
       [-0.29650368, -0.52652777, -0.51731951]])

In [ ]:
r

array([[-1.42599304, -0.47598517, -0.42611509],
       [ 0.        , -0.56968678, -0.87233584],
       [ 0.        ,  0.        ,  0.4316517 ]])

In [ ]:
# for m x n matrix a, q is m x m and r is m x n
# if m > n, q^T @ q is identity matrix
q.T @ q

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 5.55111512e-17],
       [0.00000000e+00, 5.55111512e-17, 1.00000000e+00]])

In [ ]:
# but q @ q^T is not identity matrix
q @ q.T

array([[ 0.4832594 , -0.01929719,  0.06130727,  0.4432488 ,  0.22162872],
       [-0.01929719,  0.96957718, -0.13921652, -0.01012547,  0.09818925],
       [ 0.06130727, -0.13921652,  0.31856919, -0.17968713,  0.40206415],
       [ 0.4432488 , -0.01012547, -0.17968713,  0.59582883, -0.10934966],
       [ 0.22162872,  0.09818925,  0.40206415, -0.10934966,  0.6327654 ]])

In [ ]:
# full QR factorization
(q, r) = np.linalg.qr(a, mode='complete')

In [ ]:
q

array([[-0.68664483,  0.0566785 , -0.09255171, -0.66375158, -0.27599719],
       [-0.11881553, -0.74328582,  0.63481197,  0.04138305, -0.16944104],
       [-0.04057488, -0.24080918, -0.50885539,  0.39399452, -0.72539584],
       [-0.65179827,  0.33029257,  0.24878636,  0.62878495,  0.09381181],
       [-0.29650368, -0.52652777, -0.51731951,  0.08437471,  0.60009625]])

In [ ]:
r

array([[-1.42599304, -0.47598517, -0.42611509],
       [ 0.        , -0.56968678, -0.87233584],
       [ 0.        ,  0.        ,  0.4316517 ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ]])

In [ ]:
# q^T @ q and q @ q^T are both identity matrix
print(q.T @ q)
print()
print(q @ q.T)

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00 -1.42247325e-16
  -2.77555756e-17]
 [ 0.00000000e+00  1.00000000e+00  5.55111512e-17 -1.38777878e-17
   0.00000000e+00]
 [ 0.00000000e+00  5.55111512e-17  1.00000000e+00 -3.46944695e-17
  -5.55111512e-17]
 [-1.42247325e-16 -1.38777878e-17 -3.46944695e-17  1.00000000e+00
  -4.85722573e-17]
 [-2.77555756e-17  0.00000000e+00 -5.55111512e-17 -4.85722573e-17
   1.00000000e+00]]

[[ 1.00000000e+00 -6.93889390e-18  5.55111512e-17 -5.20417043e-17
   2.77555756e-17]
 [-6.93889390e-18  1.00000000e+00 -6.93889390e-17  2.77555756e-17
  -4.16333634e-17]
 [ 5.55111512e-17 -6.93889390e-17  1.00000000e+00 -4.16333634e-17
   5.55111512e-17]
 [-5.20417043e-17  2.77555756e-17 -4.16333634e-17  1.00000000e+00
  -6.24500451e-17]
 [ 2.77555756e-17 -4.16333634e-17  5.55111512e-17 -6.24500451e-17
   1.00000000e+00]]
